Server:
  servlet:
    context-path: /poudlard
spring:
  datasource:
    dbcp2:
      initial-size: 5
      max-total: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/poudlard?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
